# This file is machine-generated - editing it directly is not advised

[[UnsafeArrays]]
git-tree-sha1 = "9740b414f85ec2fa9135066f81b1fb14212befd6"
uuid = "c4a57d5a-5b31-53a6-b365-19f8c011fbd6"
version = "1.0.1"
