name = "SlidingDistancesBase"
uuid = "25b0cc0c-38e4-462f-a11d-8564868c562d"
authors = ["Fredrik Bagge Carlson"]
version = "0.1.1"

[deps]
UnsafeArrays = "c4a57d5a-5b31-53a6-b365-19f8c011fbd6"

[compat]
julia = "1"
UnsafeArrays = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
